# -*- coding: utf-8 -*-
"""Naveed_midterm.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NRt4CyBrl7WM1LztlFt3eQXt2dpo5zsl
"""

# NAVEED HAYDER (0344-1344885) mn815325@gmail.com  [ MID-TERM EXAM ]

#Question no.1 : Write a Python program to do arithmetical operations addition and division.

e = float(input("Enter the first number for addition "))
f = float(input("Enter the second number for addition "))
g=e+f
print("sum :",g)

qw = float(input("Enter the dividend for division "))
er = float(input("Enter the divisor for division "))
gh=qw/er
print("division :",gh)

a = int(input("Enter Number "))
b = int(input("Enter Number "))
c=a**b
print("sum :",c)

x = int(input("Enter Divident "))
y = int(input("Enter Divider "))
c=x//y
print("sum :",c)

#Question No.2: Write a Python program to find the area of a triangle

ui = float(input("Enter the length of the base of the triangle "))
iu = float(input("Enter the height of the triangle "))
AA=(ui*iu)/2
print("The area of the triangle is :",AA)

# Question Number 3: Write a Python program to convert Celsius to Fahrenheit.

Celsius = int(input("Enter temperature in Celsius :\n"))
Fahrenheit = (9/5 * Celsius ) + 32
print("Temperature in Fahrenheit :", Fahrenheit)

# Question Number 4 : Write a Python program that return all datatypes that we discussed in the class.

m=int(input("Enter any number"))
print("The data type of 19 is " ,type(m))
n=float(input("Enter any point number"))
print("The data type of 16.5 is " ,type(n))
o=str(input("Enter any name"))
print("The data type of your name is " ,type(o))
p=bool(input("Enter any true value"))
print("The data type of True is " ,type(p))
q= [1, 2, 3]
print("The data type of [1, 2, 3] is " ,type(q))
r=tuple(input("Enter any tuple value"))
print("The data type of (1, 2, 3) is " ,type(r))
s=set(input("Enter any set value"))
print("The data type of {1, 2, 3} is " ,type(s))

